version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:17-jdk  # Use an OpenJDK 17 image for Java projects
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout  # Checkout code from GitHub
      - run:
          name: Set up Maven
          command: |
            apt-get update && apt-get install -y maven
      - run:
          name: Build the project
          command: mvn clean install  # Replace this with your specific build command (Maven, Gradle, etc.)

  sonarqube-scan:
    executor: java-executor
    steps:
      - checkout  # Checkout code from GitHub
      - run:
          name: Install SonarQube Scanner
          command: |
            curl -sSLo /usr/local/bin/sonar-scanner https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip -d /usr/local/bin/
            rm sonar-scanner-cli-4.6.2.2472-linux.zip
      - run:
          name: SonarQube scan
          command: |
            sonar-scanner -Dsonar.projectKey=apds-poe-mrjl -Dsonar.organization=apds-poe-mrjl -Dsonar.sources=src  # Update this with actual values for your project

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - sonarqube-scan:
          requires:
            - build