version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:17-jdk-slim  # Updated image
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run SonarQube Scan
          command: sonar-scanner -Dsonar.projectKey=apds-poe-mrjl -Dsonar.organization=apds-poe-mrjl -Dsonar.sources=src

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
