jobs:
  build-and-scan:
    executor:
      docker:
        - image: node:18
      working_directory: ~/repo

    steps:
      - checkout

      # Set up environment variables for SonarQube
      - run:
          name: Set up SonarQube environment variables
          command: |
            echo 'export SONAR_TOKEN=${SONAR_TOKEN2}' >> $BASH_ENV
            echo 'export SONAR_PROJECT_KEY="APDS-POE-MRJL_APDS-POE"' >> $BASH_ENV
            echo 'export SONAR_ORGANIZATION="apds-poe-mrjl"' >> $BASH_ENV
            echo 'export SONAR_HOST_URL="https://sonarcloud.io"' >> $BASH_ENV
            source $BASH_ENV

      # Install project dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Install sonar-scanner locally
      - run:
          name: Install sonar-scanner locally
          command: npm install sonar-scanner

      # Ensure sonar-scanner has execute permissions
      - run:
          name: Set permissions for sonar-scanner
          command: chmod +x ./node_modules/sonar-scanner/bin/sonar-scanner

      # Run SonarQube scan using npx
      - run:
          name: Run SonarQube scan
          command: |
            npx sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.sources=./src \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN2
