version: 2.1

executors:
  node-executor:
    docker:
      - image: node:18  # Using the official Node image
    working_directory: ~/repo

jobs:
  build-and-scan:
    executor: node-executor
    steps:
      # Step 1: Checkout the code
      - checkout

      # Step 2: Set up SonarCloud environment variables
      - run:
          name: Set up SonarCloud environment variables
          command: |
            echo 'export SONAR_TOKEN=${SONAR_TOKEN2}' >> $BASH_ENV  # Ensure you set this as an environment variable in CircleCI
            echo 'export SONAR_PROJECT_KEY="APDS-POE-MRJL_APDS-POE"' >> $BASH_ENV
            echo 'export SONAR_ORGANIZATION="apds-poe-mrjl"' >> $BASH_ENV
            echo 'export SONAR_HOST_URL="SONAR_HOST_URL"' >> $BASH_ENV
            source $BASH_ENV

      # Step 3: Install project dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Step 4: Install SonarScanner globally (this is the official scanner for SonarCloud)
      - run:
          name: Install SonarScanner globally
          command: npm install -g sonar-scanner

      # Step 5: Run SonarCloud scan using sonar-scanner
      - run:
          name: Run SonarCloud scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.sources=./src \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN  # This is the authentication token

workflows:
  version: 2
  build_and_scan_workflow:
    jobs:
      - build-and-scan
