# .circleci/config.yml

version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18
    working_directory: ~/repo

jobs:
  build-and-scan:
    executor: node-executor

    steps:
      - checkout

      # Set up environment variables for SonarQube
      - run:
          name: Set up SonarQube environment variables
          command: |
            echo 'export SONAR_TOKEN=${SONAR_TOKEN2}' >> $BASH_ENV
            echo 'export SONAR_PROJECT_KEY="APDS-POE-MRJL_APDS-POE"' >> $BASH_ENV
            echo 'export SONAR_ORGANIZATION="apds-poe-mrjl"' >> $BASH_ENV
            echo 'export SONAR_HOST_URL="https://sonarcloud.io"' >> $BASH_ENV
            source $BASH_ENV

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Run SonarQube scan
      - run:
          name: Run SonarQube scan
          command: |
            npx sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.sources=./src \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN2
