name: Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to another OS if required, e.g., 'windows-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your repository

      # Set up Node.js (If using Node.js, adjust version as necessary)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust this to your Node.js version

      # Install dependencies (for Node.js, assumes you have package.json)
      - name: Install dependencies
        run: npm install  # Or `yarn install` if you're using Yarn

      # Run your build or tests (adjust this to your specific setup)
      - name: Build project
        run: npm run build  # Adjust the script based on your package.json, or use another build command

      # Run SonarCloud analysis
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v3
        with:
          args: -Dsonar.projectKey=apds-poe-mrjl -Dsonar.organization=apds-poe-mrjl
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
