name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17 (required for SonarQube)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build your project using Gradle (if applicable)
      - name: Build with Gradle
        run: ./gradlew build  # Adjust if you're using a different build command
        working-directory: ./APDS-POE  # Adjust if your Gradle files are in a subdirectory

      # Step 4: Run SonarQube analysis
      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v3
        with:
          args: -Dsonar.projectKey=apds-poe-mrjl -Dsonar.organization=apds-poe-mrjl
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN2 }}  # Make sure the SONAR_TOKEN is set as a secret in your GitHub repository
          SONAR_HOST_URL: https://sonarcloud.io  # URL of your SonarQube/SonarCloud instance
