name: Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Add the distribution (e.g., 'temurin', 'adoptopenjdk')

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run SonarCloud analysis
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v3
        with:
          args: -Dsonar.projectKey=apds-poe-mrjl -Dsonar.organization=apds-poe-mrjl
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      # Optionally, if you have tests defined in your package.json:
      - name: Run tests
        run: npm test  # If your project has tests defined

