name: Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Use Java 17
          distribution: 'temurin'  # Use Eclipse Temurin JDK distribution

      # Step 3: List directory structure (optional for debugging)
      - name: List directory structure
        run: ls -R

      # Step 4: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build  # Adjust this if your Gradle task is different
        working-directory: ./APDS-POE/frontend  # Ensure the correct working directory for Gradle

      # Step 5: Run SonarCloud analysis
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: |
            -Dsonar.projectKey=apds-poe-mrjl
            -Dsonar.organization=apds-poe-mrjl
            -Dsonar.sources=./APDS-POE/src  # Adjust source directory as needed
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN2 }}  # Use GitHub secret for security
