name: Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Gradle (if not already installed on CI)
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
          unzip gradle-7.5-bin.zip
          sudo mv gradle-7.5 /opt/gradle
          echo 'export PATH=$PATH:/opt/gradle/bin' >> ~/.bashrc
          source ~/.bashrc

      # Build your project using Gradle (no gradlew wrapper)
      - name: Build with Gradle
        run: gradle build
        working-directory: ./APDS-POE  # Adjust this path if needed

      # Run SonarCloud analysis
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v3
        with:
          args: -Dsonar.projectKey=apds-poe-mrjl -Dsonar.organization=apds-poe-mrjl
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
