name: Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV
          echo "SONAR_PROJECT_KEY=APDS-POE-MRJL_APDS-POE" >> $GITHUB_ENV
          echo "SONAR_ORGANIZATION=apds-poe-mrjl" >> $GITHUB_ENV
          echo "SONAR_HOST_URL=https://sonarcloud.io" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarqube-scan-action@v3
        with:
          args: -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}

      # Optionally, run tests
      - name: Run tests
        run: npm test
