name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main  # Trigger on push to main branch, adjust as needed
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this based on your environment (e.g., windows-latest)

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (for both building and SonarQube)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # You can use 'openjdk' or 'temurin'

      # Step 3: Build your project (for example, using Maven or Gradle)
      - name: Build with Maven
        run: |
          mvn clean install # Replace with your specific build command (e.g., for Maven or Gradle)

      # Step 4: Run SonarQube analysis
      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v3
        with:
          args: -Dsonar.projectKey=apds-poe-mrjl -Dsonar.organization=apds-poe-mrjl
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ensure you have a SONAR_TOKEN stored in GitHub secrets
          SONAR_HOST_URL: https://sonarcloud.io  # If you use SonarCloud; for self-hosted use your server URL
