name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify your project's Java version

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        with:
          args: >
            -Dsonar.projectKey=<your_project_key>
            -Dsonar.organization=<your_organization_key>
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
